version: '3.8'

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=email_automation
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - email-automation
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d email_automation"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/email_automation
    env_file:
      - .env 
    volumes:
      # For development: mount source code for hot reload (optional)
      - ./backend:/app
    networks:
      - email-automation
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - email-automation
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  email-automation:
    driver: bridge
